[package]
name = "read_dht11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rppal = { version = "0.13.1", features = ["hal"] }
thiserror = "1.0"
structopt = "0.3.26"